### ISSUE TITLE
render Online is error! action 'view' is not supported for filetype 'ipynb'

### ISSUE THREAD

**Issue by arnodjiang** [datawhalechina/powerful-numpy#1]
In `readme.md` if I click content directly, then will raise error: 

`action 'view' is not supported for filetype 'ipynb'`

so please fix it, thanks.

**Comment by hscspring** [comment]
sorry i'm late
it seems that githubcontent does not render ipyhb any more  
so i changed to nbviewer, it works well. hope that helps

thanks for reading.

**Comment by thejiangcj** [comment]
Thanks for your contribution, it works.

**Comment by arnodjiang** [comment]
> sorry i'm late it seems that githubcontent does not render ipyhb any more so i changed to nbviewer, it works well. hope that helps
> 
> thanks for reading.

Thanks for your contribution, it works.
